//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadmap.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdm_documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rdm_documents()
        {
            this.rdm_documents1 = new HashSet<rdm_documents>();
        }
    
        public int id { get; set; }
        public string documentUrl { get; set; }
        public Nullable<int> contractorID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> parentDocumentID { get; set; }
        public string documentNumber { get; set; }
        public Nullable<decimal> sum { get; set; }
        public string description { get; set; }
        public int statusID { get; set; }
        public int typeID { get; set; }
    
        public virtual rdm_contractors rdm_contractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rdm_documents> rdm_documents1 { get; set; }
        public virtual rdm_documents rdm_documents2 { get; set; }
        public virtual rdm_documentStatuses rdm_documentStatuses { get; set; }
        public virtual rdm_documentTypes rdm_documentTypes { get; set; }
    }
}
